i, j = input("숫자 두개를 입력해주세요 : ").split()
i = int(i)
j = int(j)

print("더하기: i + j = ", i + j)
print("빼기: i - j = ", i - j)
print("곱하기: i * j = ", i * j)
print("나누기: i / j = ", i / j)
print("나머지없이: i // j = ", i // j)
print("나머지만: i % j = ", i % j)