seeun = input('숫자 2개를 입력해주세요!')
a = seeun.split()
print('더하기는:',int(a[0]) + int(a[1]))
print('빼기:', int(a[0]) - int(a[1]))
print('곱하기:', int(a[0]) * int(a[1]))
print('제곱:', int(a[0]) ** int(a[1]))
print('나누기:', int(a[0]) / int(a[1]))
print('나머지 없이:', int(a[0]) // int(a[1]))
print('나머지만:', int(a[0]) % int(a[1]))