print("계산기입니다")

list = str(input("숫자 두개를 입력해주세요 :")).split(',')
a= int(list[0])
b= int(list[1])
print("더하기 : ", a+b)
print("빼기 : ", a-b)
print("곱하기 : ", a*b)
print("나누기 : ", a/b)
print("몫: ", a//b)
print("나머지 : ", a%b)