list = str(input("숫자 두개를 입력해주세요.")).split(",")
print("더하기 : ",list[0] ,"+", list[1], "=", int(list[0]) + int(list[1]))
print("빼기 : ",list[0] ,"-", list[1], "=", int(list[0]) - int(list[1]))
print("곱하기 : ",list[0] ,"*", list[1], "=", int(list[0]) * int(list[1]))
print("나누기 : ",list[0] ,"/", list[1], "=", int(list[0]) / int(list[1]))
print("나머지없이 : ",list[0] ,"//", list[1], "=", int(list[0]) // int(list[1]))
print("나머지만 : ",list[0] ,"%", list[1], "=", int(list[0]) % int(list[1]))